# Data Cleaning

In [1]:
import pandas as pd

In [2]:
#loading the dataset
games = pd.read_csv('data/games.csv')
games

,Unnamed: 0,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,0,42022,1610612752,NYK,New York Knicks,42200204,2023-05-08,NYK @ MIA,L,240,...,0.750,8,27,35,21,5,4,16,23,-8.0
1,1,42022,1610612744,GSW,Golden State Warriors,42200234,2023-05-08,GSW @ LAL,L,239,...,0.750,9,31,40,29,9,2,16,22,-3.0
2,2,42022,1610612748,MIA,Miami Heat,42200204,2023-05-08,MIA vs. NYK,W,239,...,0.727,13,31,44,28,7,4,12,21,8.0
3,3,42022,1610612747,LAL,Los Angeles Lakers,42200234,2023-05-08,LAL vs. GSW,W,240,...,1.000,8,34,42,21,8,1,14,15,3.0
4,4,42022,1610612738,BOS,Boston Celtics,42200214,2023-05-07,BOS @ PHI,L,264,...,0.727,13,31,44,25,3,12,10,21,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10323,10323,22019,1610612752,NYK,New York Knicks,21900010,2019-10-23,NYK @ SAS,L,239,...,0.722,5,34,39,24,16,1,14,32,-9.0
10324,10324,22019,1610612761,TOR,Toronto Raptors,21900001,2019-10-22,TOR vs. NOP,W,265,...,0.842,16,41,57,23,7,3,16,24,8.0
10325,10325,22019,1610612747,LAL,Los Angeles Lakers,21900002,2019-10-22,LAL @ LAC,L,238,...,0.714,9,32,41,20,4,7,14,24,-10.0
10326,10326,22019,1610612740,NOP,New Orleans Pelicans,21900001,2019-10-22,NOP @ TOR,L,265,...,0.850,16,37,53,30,4,9,19,34,-8.0
10327,10327,22019,1610612746,LAC,LA Clippers,21900002,2019-10-22,LAC vs. LAL,W,239,...,0.708,11,34,45,24,8,5,14,25,10.0

In [3]:
#dropping column 'Unnamed: 0' that is not useful for our purposes
games = games.drop(columns = 'Unnamed: 0')
games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42022,1610612752,NYK,New York Knicks,42200204,2023-05-08,NYK @ MIA,L,240,101,...,0.750,8,27,35,21,5,4,16,23,-8.0
1,42022,1610612744,GSW,Golden State Warriors,42200234,2023-05-08,GSW @ LAL,L,239,101,...,0.750,9,31,40,29,9,2,16,22,-3.0
2,42022,1610612748,MIA,Miami Heat,42200204,2023-05-08,MIA vs. NYK,W,239,109,...,0.727,13,31,44,28,7,4,12,21,8.0
3,42022,1610612747,LAL,Los Angeles Lakers,42200234,2023-05-08,LAL vs. GSW,W,240,104,...,1.000,8,34,42,21,8,1,14,15,3.0
4,42022,1610612738,BOS,Boston Celtics,42200214,2023-05-07,BOS @ PHI,L,264,115,...,0.727,13,31,44,25,3,12,10,21,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10323,22019,1610612752,NYK,New York Knicks,21900010,2019-10-23,NYK @ SAS,L,239,111,...,0.722,5,34,39,24,16,1,14,32,-9.0
10324,22019,1610612761,TOR,Toronto Raptors,21900001,2019-10-22,TOR vs. NOP,W,265,130,...,0.842,16,41,57,23,7,3,16,24,8.0
10325,22019,1610612747,LAL,Los Angeles Lakers,21900002,2019-10-22,LAL @ LAC,L,238,102,...,0.714,9,32,41,20,4,7,14,24,-10.0
10326,22019,1610612740,NOP,New Orleans Pelicans,21900001,2019-10-22,NOP @ TOR,L,265,122,...,0.850,16,37,53,30,4,9,19,34,-8.0
10327,22019,1610612746,LAC,LA Clippers,21900002,2019-10-22,LAC vs. LAL,W,239,112,...,0.708,11,34,45,24,8,5,14,25,10.0

In [4]:
# Narrow down our dataset down to previous wins and losses as well as the associated plus minus count.
games = games[['TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'PLUS_MINUS']]
games

                   TEAM_NAME   GAME_ID   GAME_DATE      MATCHUP WL  PLUS_MINUS
0            New York Knicks  42200204  2023-05-08    NYK @ MIA  L        -8.0
1      Golden State Warriors  42200234  2023-05-08    GSW @ LAL  L        -3.0
2                 Miami Heat  42200204  2023-05-08  MIA vs. NYK  W         8.0
3         Los Angeles Lakers  42200234  2023-05-08  LAL vs. GSW  W         3.0
4             Boston Celtics  42200214  2023-05-07    BOS @ PHI  L        -1.0
...                      ...       ...         ...          ... ..         ...
10323        New York Knicks  21900010  2019-10-23    NYK @ SAS  L        -9.0
10324        Toronto Raptors  21900001  2019-10-22  TOR vs. NOP  W         8.0
10325     Los Angeles Lakers  21900002  2019-10-22    LAL @ LAC  L       -10.0
10326   New Orleans Pelicans  21900001  2019-10-22    NOP @ TOR  L        -8.0
10327            LA Clippers  21900002  2019-10-22  LAC vs. LAL  W        10.0

[10328 rows x 6 columns]

In [5]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10328 entries, 0 to 10327
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   TEAM_NAME   10328 non-null  object
 1   GAME_ID     10328 non-null  int64
 2   GAME_DATE   10328 non-null  object
 3   MATCHUP     10328 non-null  object
 4   WL          10328 non-null  object
 5   PLUS_MINUS  10328 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 484.2+ KB

In [6]:
# We want to change the dtype of Game_date from an object Date Time format.
games['GAME_DATE'] = pd.to_datetime(games['GAME_DATE'])

/tmp/ipykernel_36598/3181382655.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games['GAME_DATE'] = pd.to_datetime(games['GAME_DATE'])

In [7]:
games['GAME_DATE']

0       2023-05-08
1       2023-05-08
2       2023-05-08
3       2023-05-08
4       2023-05-07
           ...
10323   2019-10-23
10324   2019-10-22
10325   2019-10-22
10326   2019-10-22
10327   2019-10-22
Name: GAME_DATE, Length: 10328, dtype: datetime64[ns]

In [8]:
# Now we can sort by date from in ascending order, from oldest to most recent.
games = games.sort_values('GAME_DATE')
games

                   TEAM_NAME   GAME_ID  GAME_DATE      MATCHUP WL  PLUS_MINUS
10327            LA Clippers  21900002 2019-10-22  LAC vs. LAL  W        10.0
10324        Toronto Raptors  21900001 2019-10-22  TOR vs. NOP  W         8.0
10326   New Orleans Pelicans  21900001 2019-10-22    NOP @ TOR  L        -8.0
10325     Los Angeles Lakers  21900002 2019-10-22    LAL @ LAC  L       -10.0
10323        New York Knicks  21900010 2019-10-23    NYK @ SAS  L        -9.0
...                      ...       ...        ...          ... ..         ...
4             Boston Celtics  42200214 2023-05-07    BOS @ PHI  L        -1.0
3         Los Angeles Lakers  42200234 2023-05-08  LAL vs. GSW  W         3.0
2                 Miami Heat  42200204 2023-05-08  MIA vs. NYK  W         8.0
1      Golden State Warriors  42200234 2023-05-08    GSW @ LAL  L        -3.0
0            New York Knicks  42200204 2023-05-08    NYK @ MIA  L        -8.0

[10328 rows x 6 columns]

## Feature Engineering

In [9]:
# Now we will add features that will help in building our predictive model.
# We want to measure how well each team preformed before the current game.
# We will add the average plus minus score for the last 10 games for each team 
games['AVG_PLUS_MINUS_LAST10'] = games.groupby('TEAM_NAME')['PLUS_MINUS'].transform(lambda x: x.rolling(10, closed='left').mean())
games

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS,AVG_PLUS_MINUS_LAST10
10327,LA Clippers,21900002,2019-10-22,LAC vs. LAL,W,10.0,NaN
10324,Toronto Raptors,21900001,2019-10-22,TOR vs. NOP,W,8.0,NaN
10326,New Orleans Pelicans,21900001,2019-10-22,NOP @ TOR,L,-8.0,NaN
10325,Los Angeles Lakers,21900002,2019-10-22,LAL @ LAC,L,-10.0,NaN
10323,New York Knicks,21900010,2019-10-23,NYK @ SAS,L,-9.0,NaN
...,...,...,...,...,...,...,...
4,Boston Celtics,42200214,2023-05-07,BOS @ PHI,L,-1.0,8.0
3,Los Angeles Lakers,42200234,2023-05-08,LAL vs. GSW,W,3.0,5.9
2,Miami Heat,42200204,2023-05-08,MIA vs. NYK,W,8.0,4.6
1,Golden State Warriors,42200234,2023-05-08,GSW @ LAL,L,-3.0,0.7
0,New York Knicks,42200204,2023-05-08,NYK @ MIA,L,-8.0,-0.6

In [10]:
games[games['TEAM_NAME']=='Los Angeles Lakers'].head(35)

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS,AVG_PLUS_MINUS_LAST10
10325,Los Angeles Lakers,21900002,2019-10-22,LAL @ LAC,L,-10.0,NaN
10288,Los Angeles Lakers,21900025,2019-10-25,LAL vs. UTA,W,9.0,NaN
10252,Los Angeles Lakers,21900040,2019-10-27,LAL vs. CHA,W,19.0,NaN
10225,Los Angeles Lakers,21900054,2019-10-29,LAL vs. MEM,W,29.0,NaN
10178,Los Angeles Lakers,21900074,2019-11-01,LAL @ DAL,W,9.0,NaN
10157,Los Angeles Lakers,21900088,2019-11-03,LAL @ SAS,W,7.0,NaN
10131,Los Angeles Lakers,21900100,2019-11-05,LAL @ CHI,W,6.0,NaN
10096,Los Angeles Lakers,21900126,2019-11-08,LAL vs. MIA,W,15.0,NaN
10062,Los Angeles Lakers,21900139,2019-11-10,LAL vs. TOR,L,-9.0,NaN
10028,Los Angeles Lakers,21900151,2019-11-12,LAL @ PHX,W,8.0,NaN
10017,Los Angeles Lakers,21900159,2019-11-13,LAL vs. GSW,W,26.0,8.3
9991,Los Angeles Lakers,21900174,2019-11-15,LAL vs. SAC,W,2.0,11.9
9954,Los Angeles Lakers,21900188,2019-11-17,LAL vs. ATL,W,21.0,11.2
9932,Los Angeles Lakers,21900201,2019-11-19,LAL vs. OKC,W,5.0,11.4
9882,Los Angeles Lakers,21900220,2019-11-22,LAL @ OKC,W,3.0,9.0
9861,Los Angeles Lakers,21900232,2019-11-23,LAL @ MEM,W,1.0,8.4
9833,Los Angeles Lakers,21900249,2019-11-25,LAL @ SAS,W,10.0,7.8
9804,Los Angeles Lakers,21900264,2019-11-27,LAL @ NOP,W,4.0,8.2
9777,Los Angeles Lakers,21900279,2019-11-29,LAL vs. WAS,W,22.0,7.1
9759,Los Angeles Lakers,21900287,2019-12-01,LAL vs. DAL,L,-14.0,10.2
9720,Los Angeles Lakers,21900304,2019-12-03,LAL @ DEN,W,9.0,8.0
9715,Los Angeles Lakers,21900314,2019-12-04,LAL @ UTA,W,25.0,6.3
9676,Los Angeles Lakers,21900329,2019-12-06,LAL @ POR,W,23.0,8.6
9651,Los Angeles Lakers,21900342,2019-12-08,LAL vs. MIN,W,17.0,8.8
9611,Los Angeles Lakers,21900358,2019-12-11,LAL @ ORL,W,9.0,10.0
9583,Los Angeles Lakers,21900374,2019-12-13,LAL @ MIA,W,3.0,10.6
9551,Los Angeles Lakers,21900390,2019-12-15,LAL @ ATL,W,5.0,10.8
9519,Los Angeles Lakers,21900402,2019-12-17,LAL @ IND,L,-3.0,10.3
9494,Los Angeles Lakers,21900417,2019-12-19,LAL @ MIL,L,-7.0,9.6
9451,Los Angeles Lakers,21900443,2019-12-22,LAL vs. DEN,L,-24.0,6.7
9411,Los Angeles Lakers,21900458,2019-12-25,LAL vs. LAC,L,-5.0,5.7
9361,Los Angeles Lakers,21900484,2019-12-28,LAL @ POR,W,8.0,4.3
9350,Los Angeles Lakers,21900490,2019-12-29,LAL vs. DAL,W,13.0,2.6
9314,Los Angeles Lakers,21900507,2020-01-01,LAL vs. PHX,W,10.0,1.6
9287,Los Angeles Lakers,21900522,2020-01-03,LAL vs. NOP,W,10.0,0.9

In [11]:
# Now we would like to consider home court advantage. 
# We have to seperate the home and away games to be able to analyze this so we use the MATCHUP column to organize this. 
here_or_there = games['MATCHUP'].str.contains('@')
AWAY_GAMES = games[here_or_there]
HOME_GAMES = games[~here_or_there]

In [12]:
HOME_GAMES.shape

(5164, 7)

In [13]:
AWAY_GAMES.shape

(5164, 7)

In [14]:
HOME_GAMES

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS,AVG_PLUS_MINUS_LAST10
10327,LA Clippers,21900002,2019-10-22,LAC vs. LAL,W,10.0,NaN
10324,Toronto Raptors,21900001,2019-10-22,TOR vs. NOP,W,8.0,NaN
10304,Miami Heat,21900007,2019-10-23,MIA vs. MEM,W,19.0,NaN
10306,Charlotte Hornets,21900003,2019-10-23,CHA vs. CHI,W,1.0,NaN
10307,Utah Jazz,21900011,2019-10-23,UTA vs. OKC,W,5.0,NaN
...,...,...,...,...,...,...,...
9,Los Angeles Lakers,42200233,2023-05-06,LAL vs. GSW,W,30.0,4.0
7,Philadelphia 76ers,42200214,2023-05-07,PHI vs. BOS,W,1.0,0.9
6,Phoenix Suns,42200224,2023-05-07,PHX vs. DEN,W,5.0,-0.8
3,Los Angeles Lakers,42200234,2023-05-08,LAL vs. GSW,W,3.0,5.9
2,Miami Heat,42200204,2023-05-08,MIA vs. NYK,W,8.0,4.6

In [15]:
AWAY_GAMES

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS,AVG_PLUS_MINUS_LAST10
10326,New Orleans Pelicans,21900001,2019-10-22,NOP @ TOR,L,-8.0,NaN
10325,Los Angeles Lakers,21900002,2019-10-22,LAL @ LAC,L,-10.0,NaN
10323,New York Knicks,21900010,2019-10-23,NYK @ SAS,L,-9.0,NaN
10302,Minnesota Timberwolves,21900006,2019-10-23,MIN @ BKN,W,1.0,NaN
10303,Washington Wizards,21900009,2019-10-23,WAS @ DAL,L,-8.0,NaN
...,...,...,...,...,...,...,...
10,New York Knicks,42200203,2023-05-06,NYK @ MIA,L,-19.0,2.2
5,Denver Nuggets,42200224,2023-05-07,DEN @ PHX,L,-5.0,7.5
4,Boston Celtics,42200214,2023-05-07,BOS @ PHI,L,-1.0,8.0
1,Golden State Warriors,42200234,2023-05-08,GSW @ LAL,L,-3.0,0.7
0,New York Knicks,42200204,2023-05-08,NYK @ MIA,L,-8.0,-0.6

In [16]:
# Now since we have so many duplicates because one team is home and one is away we would like to combine these for a cleaner data set to use in our prediction model.
games_merged = pd.merge(HOME_GAMES, AWAY_GAMES, on='GAME_ID', suffixes=('_HOME', '_AWAY'))
games_merged

,TEAM_NAME_HOME,GAME_ID,GAME_DATE_HOME,MATCHUP_HOME,WL_HOME,PLUS_MINUS_HOME,AVG_PLUS_MINUS_LAST10_HOME,TEAM_NAME_AWAY,GAME_DATE_AWAY,MATCHUP_AWAY,WL_AWAY,PLUS_MINUS_AWAY,AVG_PLUS_MINUS_LAST10_AWAY
0,LA Clippers,21900002,2019-10-22,LAC vs. LAL,W,10.0,NaN,Los Angeles Lakers,2019-10-22,LAL @ LAC,L,-10.0,NaN
1,Toronto Raptors,21900001,2019-10-22,TOR vs. NOP,W,8.0,NaN,New Orleans Pelicans,2019-10-22,NOP @ TOR,L,-8.0,NaN
2,Miami Heat,21900007,2019-10-23,MIA vs. MEM,W,19.0,NaN,Memphis Grizzlies,2019-10-23,MEM @ MIA,L,-19.0,NaN
3,Charlotte Hornets,21900003,2019-10-23,CHA vs. CHI,W,1.0,NaN,Chicago Bulls,2019-10-23,CHI @ CHA,L,-1.0,NaN
4,Utah Jazz,21900011,2019-10-23,UTA vs. OKC,W,5.0,NaN,Oklahoma City Thunder,2019-10-23,OKC @ UTA,L,-5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5159,Los Angeles Lakers,42200233,2023-05-06,LAL vs. GSW,W,30.0,4.0,Golden State Warriors,2023-05-06,GSW @ LAL,L,-30.0,9.3
5160,Philadelphia 76ers,42200214,2023-05-07,PHI vs. BOS,W,1.0,0.9,Boston Celtics,2023-05-07,BOS @ PHI,L,-1.0,8.0
5161,Phoenix Suns,42200224,2023-05-07,PHX vs. DEN,W,5.0,-0.8,Denver Nuggets,2023-05-07,DEN @ PHX,L,-5.0,7.5
5162,Los Angeles Lakers,42200234,2023-05-08,LAL vs. GSW,W,3.0,5.9,Golden State Warriors,2023-05-08,GSW @ LAL,L,-3.0,0.7
5163,Miami Heat,42200204,2023-05-08,MIA vs. NYK,W,8.0,4.6,New York Knicks,2023-05-08,NYK @ MIA,L,-8.0,-0.6

In [17]:
# Now we add another column for the avg plus minus difference between home and away 
games_merged['AVG_10_PLUS_MINUS_DIFF'] = games_merged['AVG_PLUS_MINUS_LAST10_HOME'] - games_merged['AVG_PLUS_MINUS_LAST10_AWAY']

In [18]:
games_merged

,TEAM_NAME_HOME,GAME_ID,GAME_DATE_HOME,MATCHUP_HOME,WL_HOME,PLUS_MINUS_HOME,AVG_PLUS_MINUS_LAST10_HOME,TEAM_NAME_AWAY,GAME_DATE_AWAY,MATCHUP_AWAY,WL_AWAY,PLUS_MINUS_AWAY,AVG_PLUS_MINUS_LAST10_AWAY,AVG_10_PLUS_MINUS_DIFF
0,LA Clippers,21900002,2019-10-22,LAC vs. LAL,W,10.0,NaN,Los Angeles Lakers,2019-10-22,LAL @ LAC,L,-10.0,NaN,NaN
1,Toronto Raptors,21900001,2019-10-22,TOR vs. NOP,W,8.0,NaN,New Orleans Pelicans,2019-10-22,NOP @ TOR,L,-8.0,NaN,NaN
2,Miami Heat,21900007,2019-10-23,MIA vs. MEM,W,19.0,NaN,Memphis Grizzlies,2019-10-23,MEM @ MIA,L,-19.0,NaN,NaN
3,Charlotte Hornets,21900003,2019-10-23,CHA vs. CHI,W,1.0,NaN,Chicago Bulls,2019-10-23,CHI @ CHA,L,-1.0,NaN,NaN
4,Utah Jazz,21900011,2019-10-23,UTA vs. OKC,W,5.0,NaN,Oklahoma City Thunder,2019-10-23,OKC @ UTA,L,-5.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5159,Los Angeles Lakers,42200233,2023-05-06,LAL vs. GSW,W,30.0,4.0,Golden State Warriors,2023-05-06,GSW @ LAL,L,-30.0,9.3,-5.3
5160,Philadelphia 76ers,42200214,2023-05-07,PHI vs. BOS,W,1.0,0.9,Boston Celtics,2023-05-07,BOS @ PHI,L,-1.0,8.0,-7.1
5161,Phoenix Suns,42200224,2023-05-07,PHX vs. DEN,W,5.0,-0.8,Denver Nuggets,2023-05-07,DEN @ PHX,L,-5.0,7.5,-8.3
5162,Los Angeles Lakers,42200234,2023-05-08,LAL vs. GSW,W,3.0,5.9,Golden State Warriors,2023-05-08,GSW @ LAL,L,-3.0,0.7,5.2
5163,Miami Heat,42200204,2023-05-08,MIA vs. NYK,W,8.0,4.6,New York Knicks,2023-05-08,NYK @ MIA,L,-8.0,-0.6,5.2

In [19]:
games_merged[['WL_HOME', 'AVG_10_PLUS_MINUS_DIFF']]

     WL_HOME  AVG_10_PLUS_MINUS_DIFF
0          W                     NaN
1          W                     NaN
2          W                     NaN
3          W                     NaN
4          W                     NaN
...      ...                     ...
5159       W                    -5.3
5160       W                    -7.1
5161       W                    -8.3
5162       W                     5.2
5163       W                     5.2

[5164 rows x 2 columns]

In [20]:
model = games_merged[['WL_HOME', 'AVG_10_PLUS_MINUS_DIFF']].dropna()

In [21]:
model

     WL_HOME  AVG_10_PLUS_MINUS_DIFF
145        W                     1.6
150        W                     5.5
153        L                    -6.3
155        L                     2.5
156        W                    -5.2
...      ...                     ...
5159       W                    -5.3
5160       W                    -7.1
5161       W                    -8.3
5162       W                     5.2
5163       W                     5.2

[4992 rows x 2 columns]

In [22]:
# Now we have a model dataframe that we would use for our prediciton regression but first we need to change the Wins and Losses to 1s and 0. 
model['WL_HOME'] = model['WL_HOME'].map({'W': 1, 'L': 0})
model

      WL_HOME  AVG_10_PLUS_MINUS_DIFF
145         1                     1.6
150         1                     5.5
153         0                    -6.3
155         0                     2.5
156         1                    -5.2
...       ...                     ...
5159        1                    -5.3
5160        1                    -7.1
5161        1                    -8.3
5162        1                     5.2
5163        1                     5.2

[4992 rows x 2 columns]

In [23]:
model.to_csv("games_model.csv")